apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cirros-extra-disk
spec:
  storageClassName: local-block-storage-csi
  volumeMode: Block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
