apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lbsp-test-from-snap
spec:
  storageClassName: local-block-storage-csi
  volumeMode: Block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  dataSource:
    kind: VolumeSnapshot
    name: lbsp-test-snap
    apiGroup: snapshot.storage.k8s.io
